# Generated by Django 3.1.12 on 2025-02-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20250210_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
    ]
