# Generated by Django 3.1.12 on 2025-02-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_booking_payment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='hostel.owner'),
        ),
    ]
