# Generated by Django 3.1.12 on 2025-02-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_auto_20250211_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelImages',
        ),
    ]
