# Generated by Django 3.1.12 on 2025-02-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_hostelimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hostel.review'),
        ),
    ]
