# Generated by Django 3.1.12 on 2025-02-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_auto_20250218_0805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
