# Generated by Django 5.1.6 on 2025-03-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0014_alter_student_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "amenity",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hostelamenities",
            name="amenity",
            field=models.ForeignKey(
                default="Water",
                on_delete=django.db.models.deletion.CASCADE,
                to="hostel.amenities",
            ),
            preserve_default=False,
        ),
    ]
